:twitter:
	:consumer_key:OZfNlNLG23gkzdh289KVgg
	:consumer_secret:ny2OX86jHN80ItBP5lXw631ztHITnFzgvmoOxZqWY
	:access_token:399747291-gFiRTo6lYJTgIRO6z93XP6Em0KSjF9sEpzP5F7Zk
	:access_token_secret:RZhGjSNencXAYY78UALlNNVhQY3cdVByjjavSyT1L4v8v